### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MarvinXu** [MarioCadenas/vscode-alias-resolver#28]
Great idea on reading a alias config file! But it just doesn't seem to work for me. Could you plz help me find why?

OS: windows 10
Project url: https://github.com/vuejs/vue
My Setting:
```json
{
  "alias-resolver.file": "scripts/alias.js"
}
```
Alias config file:
```js
const path = require('path')

const resolve = p => path.resolve(__dirname, '../', p)

module.exports = {
  vue: resolve('src/platforms/web/entry-runtime-with-compiler'),
  compiler: resolve('src/compiler'),
  core: resolve('src/core'),
  shared: resolve('src/shared'),
  web: resolve('src/platforms/web'),
  weex: resolve('src/platforms/weex'),
  server: resolve('src/server'),
  sfc: resolve('src/sfc')
}
```

**Comment by MarioCadenas** [comment]
Hi @MarvinXu ! Well, for now, it is only supported for `webpack` and `rollup` configs. As you can see in the parser, it will look for an `alias` property, either it is a key or a function.

I do want to do a lot of improvements to it, but I'm quite busy and I'll be until June or so. After that, I'll try to give support to this, and also this other issue that was opened some time ago https://github.com/MarioCadenas/vscode-alias-resolver/issues/26

**Comment by MarvinXu** [comment]
Thanks for your explanation! I am new to this parser thing, now it makes a lot of sense to me.
IMHO, for a more universal purpose, it's better to export an alias object in a single file, like it's done in Vue source project.

Then when used in webpack or rollup, you can do:
```js
// webpack
const aliases = require('./alias.js');
module.exports = {
  resolve: {
    alias: Object.assign({}, aliases),
  },
};
```
```js
// rollup
const alias = require('rollup-plugin-alias');
const aliases = require('./alias.js');
module.exports = {
  plugins: [
    alias(Object.assign({}, aliases))
  ]
}
```

**Comment by MarioCadenas** [comment]
> Thanks for your explanation! I am new to this parser thing, now it makes a lot of sense to me.
> IMHO, for a more universal purpose, it's better to export an alias object in a single file, like it's done in Vue source project.
> 
> Then when used in webpack or rollup, you can do:
> 
> ```js
> // webpack
> const aliases = require('./alias.js');
> module.exports = {
>   resolve: {
>     alias: Object.assign({}, aliases),
>   },
> };
> ```
> 
> ```js
> // rollup
> const alias = require('rollup-plugin-alias');
> const aliases = require('./alias.js');
> module.exports = {
>   plugins: [
>     alias(Object.assign({}, aliases))
>   ]
> }
> ```

Well, that is useful if you need to reuse that, but not everyone does it like that, and the "normal" thing that people do is defining their alias inside the config. This extension aims to be compatible with the "standard", but I have in mind some stuff to make it more configurable and flexible

**Comment by MarioCadenas** [comment]
It's been a long time, but this should work now, if you are still interested 😄
